[build-system]
requires = ['setuptools>=51.0',"wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests"
    ]

[tool.mypy]
mypy_path="src"
ignore_missing_imports = true