from Medical.components.data_ingestion import DataIngestion
from Medical.components.data_validation import DataValidation
from Medical.components.data_transformation import DataTransformation
from Medical.components.model_trainer import ModelTrainer