artifacts_root: artifacts
new_data_name: None

data_ingestion:
  root_dir: artifacts/data_ingestion
  S3_bucket_name: mlflow-test-own
  raw_data_name: data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  loose_files: artifacts/data_ingestion/
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  
data_transformation:
  root_dir: artifacts/data_transformation

model_trainer:
  root_dir: artifacts/model_trainer
  
